# Generated by this tap's update-possible workflow from published SHA256SUMS.
class Possible < Formula
  desc "Discover, author, and capture source-owned AI Outcomes"
  homepage "https://possible.sh"
  version "0.6.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/fraylabs/possible/releases/download/v0.6.2/possible-v0.6.2-darwin-arm64.tar.gz"
      sha256 "23b89988f167715c6c26a4862e8dc20389eb2f4a440b94c8ad2c536bf63286c1"
    end
    on_intel do
      url "https://github.com/fraylabs/possible/releases/download/v0.6.2/possible-v0.6.2-darwin-x64.tar.gz"
      sha256 "397e0b426ccb96b84c1d35d1b403afed88a9c8dea1197d129fe126cb47aac6cd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fraylabs/possible/releases/download/v0.6.2/possible-v0.6.2-linux-arm64.tar.gz"
      sha256 "101f21f61d2b399d69917568d955664d42febaaa6daa2697ff698ca7e85360a9"
    end
    on_intel do
      url "https://github.com/fraylabs/possible/releases/download/v0.6.2/possible-v0.6.2-linux-x64.tar.gz"
      sha256 "c35eda045966899ad51859f2c8cd97f5c19ce82e3cdf0e65d51f0d90c57cb3ce"
    end
  end

  def install
    bin.install "possible"
    pkgshare.install "LICENSE", "NODE-LICENSE"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/possible --version").strip
    system bin/"possible", "create", "smoke", "--product", "example/product"
    assert_match "Validated 1 Outcome", shell_output("#{bin}/possible validate")
  end
end
