# Generated by this tap's update-possible workflow from published SHA256SUMS.
class Possible < Formula
  desc "Discover, author, and capture source-owned AI Outcomes"
  homepage "https://possible.sh"
  version "0.6.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/fraylabs/possible/releases/download/v0.6.0/possible-v0.6.0-darwin-arm64.tar.gz"
      sha256 "951fb804e62aa71bfbdbece41afa6df2d5729038414118d0bc94865643ab27f4"
    end
    on_intel do
      url "https://github.com/fraylabs/possible/releases/download/v0.6.0/possible-v0.6.0-darwin-x64.tar.gz"
      sha256 "6bba6544e9ad7f0a28287ad79662119d62d2d50a3c20e0cc0d96bda61ef42fb7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fraylabs/possible/releases/download/v0.6.0/possible-v0.6.0-linux-arm64.tar.gz"
      sha256 "af9ca711831be88a0a6cb4d87948ee633ffc4e022efcd87309271c11b0b0bc3e"
    end
    on_intel do
      url "https://github.com/fraylabs/possible/releases/download/v0.6.0/possible-v0.6.0-linux-x64.tar.gz"
      sha256 "bdf3417ba2c9d3d98e5353275c27b66a8a90163cebad157c3030f946caad1551"
    end
  end

  def install
    bin.install "possible"
    pkgshare.install "LICENSE", "NODE-LICENSE"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/possible --version").strip
    system bin/"possible", "create", "smoke", "--product", "example/product"
    assert_match "Validated 1 Outcome", shell_output("#{bin}/possible validate")
  end
end
