# Generated by this tap's update-possible workflow from published SHA256SUMS.
class Possible < Formula
  desc "Discover, author, and capture source-owned AI Outcomes"
  homepage "https://possible.sh"
  version "0.5.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/fraylabs/possible/releases/download/v0.5.1/possible-v0.5.1-darwin-arm64.tar.gz"
      sha256 "ed1c75d94e5923289cb393973bd9351c7566494b6107feb0d6215c9acef631a5"
    end
    on_intel do
      url "https://github.com/fraylabs/possible/releases/download/v0.5.1/possible-v0.5.1-darwin-x64.tar.gz"
      sha256 "4c45e59c0a5ce9426466606a7ca8e6df291a0d2014f78caf488375e004be6be5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fraylabs/possible/releases/download/v0.5.1/possible-v0.5.1-linux-arm64.tar.gz"
      sha256 "7cc292c1f4cff0a75f42684ecd4f106007bcc6bea18f0d78f371e9db76b5bdd6"
    end
    on_intel do
      url "https://github.com/fraylabs/possible/releases/download/v0.5.1/possible-v0.5.1-linux-x64.tar.gz"
      sha256 "c1daf26cc7f3177657a5066bb8c592ed5ddd717c098a0f2b62daaaf7191aeacb"
    end
  end

  def install
    bin.install "possible"
    pkgshare.install "LICENSE", "NODE-LICENSE"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/possible --version").strip
    system bin/"possible", "create", "smoke", "--product", "example/product"
    assert_match "Validated 1 Outcome", shell_output("#{bin}/possible validate")
  end
end
